version: "2"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Sho12345
      MYSQL_DATABASE: root
    volumes:
      - mariadb-data:/var/lib/mariadb #データの永続化のために必要
    ports:
      - "4306:3306" #両方3306でもok。詳細は下の「番外編：DBをsequel proで可視化したい」へ

  app:
    tty: true #コンテナ上でbinding.pryするために必要
    stdin_open: true #コンテナ上でbinding.pryするために必要
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sample #ローカルのディレクトリをコンテナ上にマウント
      #- bundle:/usr/local/bundle #bundle installした後buildし直さなくてよくなる
    ports:
      - "3000:3000"
    links:
      - db

#  web:
#    build: .
#    command: bundle exec rails s -p 8000 -b '0.0.0.0'
#    volumes:
#      - .:/sample
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

volumes:
  mariadb-data:
  bundle: #bundle installした後buildし直さなくてよくなる
